server:
    port: 8080
spring:
    application:
        name: gamescore
    datasource:
        url: jdbc:postgresql://localhost:5432/gamescore3
        username: postgres
        password: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect

